polls/polls/apps/auth_service/urls.py
from django.conf.urls import url, include
from .views import login, logout, register

urlpatterns = [
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^register/', register, name='register'),
]

polls/polls/apps/poll/urls.py
from django.conf.urls import url
# from polls.apps.poll.views import user_polls, poll, add_completion_of_poll, set_user_answer, new_poll, add_poll
from polls.apps.poll.views import add_completion_of_poll, add_poll
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    # Опросы пользователя
    url(r'user_polls/(?P<user_id>\d+)/$', views.PollListView.as_view(), name='user_polls'),

    # Опрос
    url(r'poll/(?P<pk>\d+)/$', views.PollDetailView.as_view(), name='poll'),

    # Обработка завершения прохождения опрса
    url(r'poll/(?P<poll_id>\d+)/add_completion_of_poll/$', add_completion_of_poll, name='add_completion_of_poll'),

    # Обработка ответа пользователя
    url(r'set_user_answer/$', views.PollDetailView.as_view(), name='set_user_answer'),

    # Загрузка пустой страницы для создания опроса
    url(r'new_poll/$', TemplateView.as_view(template_name='create_poll.html'), name='new_poll'),

    # Сохранение опроса в базу
    url(r'add_poll/$', add_poll, name='add_poll'),

    url(r'(?P<slug>\w+)/$', views.PollDetailView.as_view(), name='poll_with_slug'),
]

polls/polls/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from polls.apps.poll import views

urlpatterns = [
    url(r'^auth/', include('polls.apps.auth_service.urls', namespace="auth_service")),
    url(r'^polls/', include('polls.apps.poll.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.PollListView.as_view(), name='index'),
    url(r'^system_statistics/$', views.SystemStatisticsTemplateView.as_view(), name='index')
]

polls/polls/apps/auth_service/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Email непременно должен быть указан')

        user = self.model(
            email=UserManager.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class ExtUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(
        'Электронная почта',
        max_length=255,
        unique=True,
        db_index=True
    )
    weight = models.FloatField(
        'Вес пользователя',
        default=0
    )
    firstname = models.CharField(
        'Фамилия',
        max_length=40,
        null=True,
        blank=True
    )
    lastname = models.CharField(
        'Имя',
        max_length=40,
        null=True,
        blank=True
    )
    middlename = models.CharField(
        'Отчество',
        max_length=40,
        null=True,
        blank=True
    )
    date_of_birth = models.DateField(
        'Дата рождения',
        null=True,
        blank=True
    )
    register_date = models.DateField(
        'Дата регистрации',
        auto_now_add=True
    )
    is_active = models.BooleanField(
        'Активен',
        default=True
    )
    is_admin = models.BooleanField(
        'Суперпользователь',
        default=False
    )

    def get_full_name(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        # TODO заглучшка
        return True

    def has_module_perms(self, app_label):
        # TODO заглучшка
        return True

    def __str__(self):
        return self.email

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

polls/polls/apps/poll/models.py
from django.db import models
from polls.apps.auth_service.models import ExtUser


class Poll(models.Model):
    class Meta:
        ordering = ('-weight', '-successful_completion_count',)
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'

    owner = models.ForeignKey(ExtUser)
    title = models.CharField(verbose_name='Название', max_length=200)
    slug = models.CharField(verbose_name='Адрес', max_length=200, null=True)
    weight = models.FloatField(verbose_name='Вес опроса', default=0)
    successful_completion_count = models.IntegerField(
        verbose_name='Количество успешных прохождений',
        default=0
    )

    not_successful_completion_count = models.IntegerField(
        verbose_name='Количество не полных прохождений',
        default=0
    )
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    class Meta:
        ordering = ('poll', )
        verbose_name = 'Вопрос опроса'
        verbose_name_plural = 'Вопросы опросов'

    poll = models.ForeignKey(Poll)
    title = models.CharField(verbose_name='Вопрос', max_length=200)
    respondents_count = models.IntegerField(
        verbose_name='Количество респондентов',
        default=0
    )

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(Question)

    title = models.CharField(verbose_name='Ответ', max_length=200)
    selection_count = models.IntegerField(
        verbose_name='Количество выборов данного ответа',
        default=0
    )

    def percentage_of_elections(self):
        elections_count = UserAnswer.objects.filter(answer=self).count()
        if elections_count == 0:
            return 0
        elections_of_this_question = UserAnswer.objects.filter(question=self.question).count()
        return elections_count / (elections_of_this_question / 100)

    def __str__(self):
        return self.title


class UserAnswer(models.Model):
    user = models.ForeignKey(ExtUser)
    question = models.ForeignKey(Question)
    answer = models.ForeignKey(Answer)

polls/polls/apps/auth_service/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model


class UserCreationForm(forms.ModelForm):
    """
    Форма регистрации пользователя
    """
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Подтверждение',
        widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароль и подтверждение не совпадают')
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('email',)


class UserChangeForm(forms.ModelForm):
    """
    Форма изменения данных пользователей
    """
    def save(self, commit=True):
        user = super(UserChangeForm, self).save(commit=False)
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['email', ]


class LoginForm(forms.Form):
    """
    Форма для входа в систему
    """
    email = forms.CharField()
    password = forms.CharField()

polls/polls/apps/auth_service/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from polls.apps.auth_service.forms import LoginForm, UserCreationForm


def login(request):
    args = dict()
    args['form'] = LoginForm()

    if request.POST:
        user_form = LoginForm(request.POST)
        if user_form.is_valid():
            user = auth.authenticate(email=user_form.cleaned_data['email'],
                                     password=user_form.cleaned_data['password'])
            if user is not None:
                auth.login(request, user)
                return redirect('/')
            else:
                args['login_error'] = 'User is not found'
                return render(request, 'login.html', args)
        else:
            args['login_error'] = 'User is not found'
            return render(request, 'login.html', args)
    else:
        return render(request, 'login.html', args)


def logout(request):
    auth.logout(request)
    return redirect("/")


def register(request):
    args = dict()
    args['form'] = UserCreationForm()
    if request.POST:
        new_user_form = UserCreationForm(request.POST)
        if new_user_form.is_valid():
            new_user_form.save()
            new_user_form = auth.authenticate(email=new_user_form.cleaned_data['email'], password=new_user_form.cleaned_data['password2'])
            auth.login(request, new_user_form)
            return redirect('/')
        else:
            args['form'] = new_user_form
    return render(request, 'registration.html', args)

polls/polls/apps/poll/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from .models import Poll, Question, Answer, UserAnswer
from polls.apps.auth_service.models import ExtUser
from django.db.models import Count, Sum
from django.views import generic


class PollListView(generic.ListView):
    template_name = 'polls.html'

    def get_queryset(self):
        if 'user_id' in self.kwargs:
            return Poll.objects.filter(owner__id=self.kwargs['user_id']).order_by('-successful_completion_count')
        else:
            return Poll.objects.all()


class PollDetailView(generic.DetailView):
    model = Poll
    template_name = 'poll.html'
    slug_field = 'slug'

    def get_object(self):
        poll_object = super(PollDetailView, self).get_object()
        if self.request.user.is_authenticated():
            poll_object.not_successful_completion_count += 1
            poll_object.save()
        return poll_object

    def post(self, request, *args, **kwargs):
        if 'answer_id' in request.POST:
            answer = Answer.objects.get(pk=request.POST.get('answer_id'))
            answer.selection_count += 1
            question = answer.question
            question.respondents_count += 1
            user = request.user
            if request.POST.get('checked') == 'true':
                if UserAnswer.objects.filter(answer=answer, question=question, user=user).count() == 0:
                    UserAnswer.objects.create(answer=answer, question=question, user=user).save()
            else:
                UserAnswer.objects.filter(answer=answer, question=question, user=user).delete()
            answer.save()
            question.save()
            return HttpResponse('answer_saved')


class SystemStatisticsTemplateView(generic.TemplateView):
    template_name = 'system_statistics.html'

    def get_context_data(self, **kwargs):
        context = dict()
        context['users_count'] = ExtUser.objects.all().count()
        context['polls_count'] = Poll.objects.all().count()
        context['successful_completion_count_sum'] = Poll.objects.\
            aggregate(Sum('successful_completion_count'))['successful_completion_count__sum']
        context['most_popular_users'] = ExtUser.objects.annotate(num_polls=Count('poll')).order_by('-num_polls')[:3]
        context['most_popular_polls'] = Poll.objects.order_by('successful_completion_count')[:3]

        return context


def add_poll(request):
    # Добавляет опрос в базу
    # Очень неудачная функция
    poll = Poll(title=request.POST.get('title'), slug=request.POST.get('slug'), owner=request.user, weight=request.POST.get('weight'))
    poll.save()
    post_keys = list(request.POST.keys())
    post_keys.remove('csrfmiddlewaretoken')
    post_keys.remove('title')
    post_keys.remove('slug')
    post_keys.remove('weight')
    post_keys.sort(reverse=True)
    questions_count = len(post_keys) // 2
    for i in range(questions_count):
        question = Question(title=request.POST.get('question_%s' % i), poll=poll)
        question.save()

        answers_titles = request.POST.getlist('answer_for_question_%s' % i)
        for answer_title in answers_titles:
            answer = Answer(title=answer_title, question=question)
            answer.save()
    return redirect('/')


def add_completion_of_poll(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    poll.successful_completion_count += 1
    poll.not_successful_completion_count -= 1
    poll.save()
    return redirect('/')

polls/polls/apps/poll/templates/create_poll.html
{% extends "main.html" %}
{% block scripts %}
    <script>
        function addQuestion(){
            var title = prompt('Введите вопрос'),
                questions_number = document.getElementsByClassName('question').length,
                container = document.getElementsByClassName('questions')[0],
                question_container = document.createElement('div'),
                answers_container = document.createElement('div'),
                question_title_input = document.createElement('input'),
                add_answer_button = document.createElement('button');

            question_container.className = 'question';
            question_container.id = 'question_container_' + questions_number;

            question_title_input.name = 'question_'+questions_number;
            question_title_input.value = title;

            answers_container.className = 'answers';

            add_answer_button.setAttribute('onclick', 'addAnswer('+questions_number+')');
            add_answer_button.innerHTML = 'Добавить ответ к этому вопросу';
            add_answer_button.type = "button";

            question_container.appendChild(question_title_input);
            question_container.appendChild(answers_container);
            question_container.appendChild(add_answer_button);

            container.appendChild(question_container);
        }

        function addAnswer(question_number){
            var title = prompt('Введите вариант ответа'),
                question_container = document.getElementById('question_container_'+question_number),
                answers_container = question_container.getElementsByClassName('answers')[0],
                answer_hidden_input = document.createElement('input'),
                answer_label = document.createElement('label');


            answer_hidden_input.type = 'checkbox';
            answer_hidden_input.value = title;
            answer_hidden_input.checked = true;
            answer_hidden_input.hidden = true;
            answer_hidden_input.name = 'answer_for_question_'+question_number;

            answer_label.innerHTML = title;

            answers_container.appendChild(answer_hidden_input);
            answers_container.appendChild(answer_label);
        }
    </script>
{% endblock scripts %}

{% block create_poll %}
    <form action="{% url 'polls:add_poll' %}" method="post">
        {% csrf_token %}
        <label class="col-sm-3">Название опроса</label> <input class="col-sm-9" name="title">
        <label  class="col-sm-3">Url для опроса</label><input  class="col-sm-9" name="slug">
        <label  class="col-sm-3">Вес опроса</label><input  class="col-sm-9" name="weight">
        <div class="questions"></div>
        <button type="button" onclick="addQuestion()">Добавить вопрос</button>
        <button type="submit">Создать опрос</button>
    </form>
{% endblock create_poll %}

polls/polls/apps/poll/templates/pagination.html
<div class="row">
    <div class="col-sm-offset-3 col-sm-3">
        <ul class="pagination">
            {% if polls.has_previous %}
                <li class="arrow">
                    <a href="/polls/page/{{ polls.previous_page_number }}/">&laquo;</a>
                </li>
            {% else %}
                <li class="arrow disabled">
                    <a href="">&laquo;</a>
                </li>
            {% endif %}
            {% for page in polls.paginator.page_range %}
                {% if page == polls.number %}
                    <li class="current">
                        <a href="/polls/page/{{ page }}/">{{ page }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="/polls/page/{{ page }}/">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if polls.has_next %}
                <li class="arrow">
                    <a href="/polls/page/{{ polls.next_page_number }}">&raquo;</a>
                </li>
            {% else %}
                <li class="arrow disabled">
                    <a href="">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

polls/polls/apps/poll/templates/poll.html
{% extends "main.html" %}

{% block scripts %}
<script>
    $(function() {
        $('[name=answer]').on('change', function(e){
            $.ajax({
                url:"{% url 'polls:set_user_answer' %}",
                type:"POST",
                data:{
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                    'answer_id': $(e.target).val(),
                    'checked': $(e.target)[0].checked
                },
                dataType:"json"
            })
        })
    });
</script>
{% endblock scripts %}

{% block poll %}
    <form method="post" action="{% url 'polls:add_completion_of_poll' poll.id %}">
        {% csrf_token %}
        <h1>{{ poll.title }}</h1>
        {% for question in poll.question_set.all %}
            <h3>{{ question.title }}</h3>
            {% for answer in question.answer_set.all %}
                {% if user.is_authenticated %}
                    {% if user.id == poll.owner.id %}
                        {{ answer.percentage_of_elections|floatformat:1 }}
                    {% else %}
                        <input type="checkbox" name="answer"
                           id="answer_{{ answer.id }}" value="{{ answer.id }}" />
                    {% endif %}
                {% endif %}
                <label for="answer_{{ answer.id }}">{{ answer.title }}</label><br />
            {% endfor %}
        {% endfor %}
        {% if user.is_authenticated %}
            <input class="btn btn-success" type="submit" value="Завершить прохождение опроса">
        {% endif %}
    </form>
{% endblock poll %}

polls/polls/apps/poll/templates/polls.html
{% extends 'main.html' %}

{% block polls %}
    {% for poll in poll_list %}
        <h3>
            <a href="{% url 'polls:poll' poll.id %}">{{ poll.title}}</a>
        </h3>
        <h4>Вес опроса: {{ poll.weight }}</h4>
{#        <h4>Вес создателя: {{ poll.owner.weight }}</h4>#}
        <h4>Прошло опрос: {{ poll.successful_completion_count }}</h4>
        <h4>Не осилило опрос: {{ poll.not_successful_completion_count }}</h4>
        <h4>Дата публикации: {{ poll.created_at }}.</h4>
        <h4>Создатель опроса: <a href="{% url 'polls:user_polls' poll.owner.id %}">{{ poll.owner }}</a>.</h4>
    {% endfor %}
{% endblock polls %}